### PR TITLE
GHC 8.4.* compat and other changes

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by sol** [comment]
@bsl in the case you aren't eager to maintain this library anymore, I can offer to take over minimal maintainership.  This are the things I would do:

- Make sure that the tests exit with exit code `/= 0` on failure
- Make sure that the library continues to compile with new versions of GHC
- Remove the `ppdot` executable

**Comment by bsl** [comment]
@sol Thank you for volunteering. I've added you as a collaborator. I appreciate your efforts.

**Comment by phischu** [comment]
I just want to bump this. A hackage release with GHC 8.4 compatibility would be great. Great library, thanks!

**Comment by bsl** [comment]
@phischu Hi, do you have any interest in being a collaborator on this repo? I don't have much time to maintain it anymore.

**Comment by bgamari** [comment]
I would be happy to help as well.

**Comment by siddharthist** [comment]
I can confirm that this builds for me with GHC 8.4+, and would like to see it merged!

**Comment by siddharthist** [comment]
@sol Thanks for putting this together!

**Pull request merged**
